### ISSUE TITLE
You may like to add this line to your plugin

### ISSUE THREAD

**Issue by CKRMK** [samuelaguilera/sar-disable-rest-api#1]
Hi Samuel,
Under
function sar_remove_rest_api_headers() {

You may like to add this line:
remove_action('wp_head', 'wp_oembed_add_discovery_links', 10);

in order to remove these lines inserted in the WP page header, that are related to the Rest API
<link rel="alternate" type="application/json+oembed" href="http://....
<link rel="alternate" type="text/xml+oembed" href="http:://...

**Comment by samuelaguilera** [comment]
Noticed this issue almost 3 years later! LOL!

Latest release (2.0) includes removal of wp_oembed_add_discovery_links action.
