### ISSUE TITLE
Adding Instead of Removing wp_oembed_add_discovery_links

### ISSUE THREAD

**Issue by TheRealMikeD** [samuelaguilera/sar-disable-rest-api#2]
On line 69 of sar-disable-rest-api.php, you are calling: 
`add_action( 'wp_head', 'wp_oembed_add_discovery_links' );`

In order to remove the wp-json/oembed links, I believe it should be:
`remove_action( 'wp_head', 'wp_oembed_add_discovery_links' );`

Making this change worked for me in testing.

Thanks!

**Comment by samuelaguilera** [comment]
Thanks for the report. It's now fixed and deployed into new version 2.1.1

**Comment by TheRealMikeD** [comment]
Awesome, thanks!
