### ISSUE TITLE
experiencing technical difficulties message

### ISSUE THREAD

**Issue by NathanielB2** [samuelaguilera/sar-disable-rest-api#3]
Hello, 

Once installed and activated if I go to {domain}/wp-json/wp/v2/user_request  I get the WordPress error page with "The site is experiencing technical difficulties.".  If I turn off your plugin and refresh the page the data loads from {domain}/wp-json/wp/v2/user_request.   

Is this the message you intended to show?  How do I change the message?

I'm updated to WordPress version 5.2.3

Thanks
Nathaniel

**Comment by NathanielB2** [comment]
I found that if comment out remove_action( 'parse_request', 'rest_api_loaded' ); the error stopped but API calls to /wp-json/wp/v2/users works again.   Also found that remove_action( 'parse_request', 'rest_api_loaded' ); breaks other plugins like Contact Form 7.   I guess the best way to really handle this is not using a plugin to block access to wp-json but use htacess instead.

**Comment by samuelaguilera** [comment]
Hello,

When you see the "The site is experiencing technical difficulties." in recent versions of WordPress, that means a PHP fatal error occurred in the site. Usually WP core will send you an email with the error message, if not, you should be able to find it in your server error_log file.

According to your description of the issue, what's happening in your site is that some plugins need the WP REST API to be available, and therefore completely disabling it is not an option for you. As you already guessed this is not a problem in my plugin, you're just turning off the REST API and other plugins in the site need it.
So you can't turn off the  REST API. As alternative you can try the "Logged In Only" option, hopefully that would be enough to prevent the error and you would be still blocking access to the REST API to anonymous visitors (like bots, scrappers, etc...).

If you block the access to the REST API end-point using the .htaccess file, you will be still breaking whatever feature of those plugins that want to use REST API, so probably you will avoid the PHP fatal error, but those features will not work.

**Comment by NathanielB2** [comment]
It's odd because I'm not getting the error_log file and I wasn't sent a WP email. I did try another plugin WP REST API Controller before using yours.  I had uninstalled it but maybe the changes I made in their plugin made was not reversed when deleting it.  The site works fine I just receive the error "The site is experiencing technical difficulties." when testing to see if REST API was disabled.
